version: '3.1'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8082:8082'
            - '50000:50000'
        image: localhost:8080/jenkins
    jenkins-slave:
        container_name: milpocitv/typetest
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        image: localhost:8082/milpotest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
        depends_on:
            - jenkins